version: "3"
services:
  server:
    container_name: "TMpro_server_test"
    build:
      context: ./server/
      target: test
    ports:
      - "3030:3030"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/TMpro_test
      - JWT_SECRET=verysecretkey
      - NODE_ENV=test
    depends_on:
      - mongo_db
    command: ["yarn", "test"]

  mongo_db:
    container_name: "TMpro_db_test"
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-test-data:/data/db

volumes:
  db-test-data:
