version: "3"
services:
  client:
    container_name: "TMpro_client"
    build:
      context: ./client/
    restart: always
    ports:
      - "5000:80"

  server:
    container_name: "TMpro_server"
    build:
      context: ./server/
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/TMpro
      - JWT_TOKEN=verysecretkey
      - PORT=5001
      - NODE_ENV=production
    depends_on:
      - mongo_db

  mongo_db:
    container_name: "TMpro_db"
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
