version: "3"
services:
  server:
    container_name: "TMpro_server_dev"
    build:
      context: ./server/
      target: development
    restart: always
    ports:
      - "3030:3030"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/TMpro
      - JWT_SECRET=verysecretkey
      - NODE_ENV=development
    depends_on:
      - mongo_db

  mongo_db:
    container_name: "TMpro_db_dev"
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-dev-data:/data/db

volumes:
  db-dev-data:
